/*
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The CreateTodoDto model module.
 * @module model/CreateTodoDto
 * @version 1.0
 */
export class CreateTodoDto {
  /**
   * Constructs a new <code>CreateTodoDto</code>.
   * @alias module:model/CreateTodoDto
   * @class
   */
  // eslint-disable-next-line no-useless-constructor
  constructor() {}

  /**
   * Constructs a <code>CreateTodoDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateTodoDto} obj Optional instance to populate.
   * @return {module:model/CreateTodoDto} The populated <code>CreateTodoDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateTodoDto();
      if (data.hasOwnProperty("isFinished"))
        obj.isFinished = ApiClient.convertToType(data["isFinished"], "Boolean");
      if (data.hasOwnProperty("description"))
        obj.description = ApiClient.convertToType(
          data["description"],
          "String"
        );
      if (data.hasOwnProperty("date"))
        obj._date = ApiClient.convertToType(data["date"], "Date");
    }
    return obj;
  }
}

/**
 * @member {Boolean} isFinished
 */
CreateTodoDto.prototype.isFinished = undefined;

/**
 * @member {String} description
 */
CreateTodoDto.prototype.description = undefined;

/**
 * @member {Date} _date
 */
CreateTodoDto.prototype._date = undefined;
