/*
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TodoDto model module.
 * @module model/TodoDto
 * @version 1.0
 */
export class TodoDto {
  /**
   * Constructs a new <code>TodoDto</code>.
   * @alias module:model/TodoDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TodoDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TodoDto} obj Optional instance to populate.
   * @return {module:model/TodoDto} The populated <code>TodoDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TodoDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('isFinished'))
        obj.isFinished = ApiClient.convertToType(data['isFinished'], 'Boolean');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
TodoDto.prototype.id = undefined;

/**
 * @member {Boolean} isFinished
 */
TodoDto.prototype.isFinished = undefined;

/**
 * @member {String} description
 */
TodoDto.prototype.description = undefined;

/**
 * @member {Date} _date
 */
TodoDto.prototype._date = undefined;

